modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/webbukkit/dynmap/issues"
license="Apache Public License v2"
[[mods]]
modId="dynmap"
version="${version}"
displayName="Dynmap"
authors="mikeprimm"
description='''
Dynamic, Google-maps style rendered maps for your Minecraft server
'''
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
[[dependencies.dynmap]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.6,)"
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="SERVER"
[[dependencies.dynmap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.6,1.21)"
    ordering="NONE"
    side="SERVER"
